export enum CompanyType {
	PRODUCTION_COMPANY = 'PRODUCTION_COMPANY',
	CONTENT_CREATOR = 'CONTENT_CREATOR',
	MUSIC_PRODUCTION = 'MUSIC_PRODUCTION',
	DISTRIBUTOR = 'DISTRIBUTOR',
	BRAND = 'BRAND',
	OTHER = 'OTHER'
}
